[database]
host = "127.0.0.1"
port = 5432
user = ""
password = ""
name = "ytcw"
sslmode = "disable"

[ytcwd]
max_video_age = "168h"
no_channel_retry_interval = "15m"
post_fetch_sleep_duration = "1m"
max_last_fetch_age = "4h"
