// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT License",
            "url": "https://github.com/mY9Yd2/ytcw/blob/main/LICENSE.md"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/categories": {
            "get": {
                "description": "Get a paginated list of categories ordered by name in ascending order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "List categories",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.PaginationResponse-content_CategoryResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/content.CategoryResponse"
                                            }
                                        },
                                        "pagination": {
                                            "$ref": "#/definitions/common.Pagination"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/channels": {
            "get": {
                "description": "Get a paginated list of channels ordered by uploader_id (YouTube handler) in ascending order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "List channels",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "category name",
                        "name": "category",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.PaginationResponse-content_ChannelResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/content.ChannelResponse"
                                            }
                                        },
                                        "pagination": {
                                            "$ref": "#/definitions/common.Pagination"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/videos": {
            "get": {
                "description": "Get a paginated list of videos ordered by created_at in descending order",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Videos"
                ],
                "summary": "List videos",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/common.PaginationResponse-content_VideoResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/content.VideoResponse"
                                            }
                                        },
                                        "pagination": {
                                            "$ref": "#/definitions/common.Pagination"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.Pagination": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer",
                    "default": 1,
                    "minimum": 1
                },
                "page_size": {
                    "type": "integer",
                    "default": 50,
                    "maximum": 50,
                    "minimum": 1
                },
                "total_pages": {
                    "type": "integer"
                },
                "total_rows": {
                    "type": "integer"
                }
            }
        },
        "common.PaginationResponse-content_CategoryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/content.CategoryResponse"
                    }
                },
                "pagination": {}
            }
        },
        "common.PaginationResponse-content_ChannelResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/content.ChannelResponse"
                    }
                },
                "pagination": {}
            }
        },
        "common.PaginationResponse-content_VideoResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/content.VideoResponse"
                    }
                },
                "pagination": {}
            }
        },
        "content.CategoryResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "content.ChannelResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/content.CategoryResponse"
                },
                "channel": {
                    "type": "string"
                },
                "channel_id": {
                    "type": "string"
                },
                "disabled_at": {
                    "type": "string"
                },
                "disabled_until": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_fetch": {
                    "type": "string"
                },
                "uploader_id": {
                    "type": "string"
                }
            }
        },
        "content.ChannelSummary": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/content.CategoryResponse"
                },
                "channel": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "content.VideoResponse": {
            "type": "object",
            "properties": {
                "channel": {
                    "$ref": "#/definitions/content.ChannelSummary"
                },
                "display_id": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "full_title": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "thumbnail": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "video_type": {
                    "$ref": "#/definitions/content.VideoType"
                }
            }
        },
        "content.VideoType": {
            "type": "string",
            "enum": [
                "regular",
                "short"
            ],
            "x-enum-varnames": [
                "VideoTypeRegular",
                "VideoTypeShort"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ytcw API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
